# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "file:///home/galera/Code/github.com/asajaroff/tofu-aws-modules///modules/iam-user"
}

include "root" {
  path = find_in_parent_folders()
}

inputs = {
  user_name = "certbot@haproxy.ams.molest.ar" # TODO: fill in value
  user_description = "A user that generates ACME self signed certificates"
  policy_description = "certbot@haproxy.ams.molest.ar can modify DNS records for certificate validation" # TODO: fill in value

  # tags = {}
  region = "us-east-1"

}
