
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/asajaroff/tofu-aws-modules.git//modules/ec2"
}

locals {
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  region_vars      = read_terragrunt_config(find_in_parent_folders("region.hcl"))
}

dependency "network" {
  config_path = "../network"
}

include "root" {
  path = find_in_parent_folders()
}

inputs = {
  pool_name = "kubernetes-the-hard-way"

  instances_map = [
    {
      name                    = "jumpbox.development.ar",
      instance_type           = "t4g.nano",
      disable_api_termination = false
      volume_size             = 10
      public                  = true
    },
    {
      name                    = "server.development.ar",
      instance_type           = "t4g.small",
      disable_api_termination = false
      volume_size             = 20
      public                  = true
    },
    {
      name                    = "node-0.development.ar",
      instance_type           = "t4g.small",
      disable_api_termination = false
      volume_size             = 20
      public                  = true
    },
    {
      name                    = "node-1.development.ar",
      instance_type           = "t4g.small",
      disable_api_termination = false
      volume_size             = 20
      public                  = true
  }]

  # Description: VPC where the resources will be created
  # Type: string
  vpc_id    = dependency.network.outputs.vpc_id
  subnet_id = dependency.network.outputs.public_subnets
  region    = local.region_vars.locals.aws_region
  os_arch   = "arm64"
  os_family = "debian"

}
