# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-west-1"
  default_tags {
    tags = { "environment" : "dev", "terragrunt" : true }
  }

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["761399334120"]
}
